### ISSUE TITLE
迅雷模块好像不行了

### ISSUE THREAD

**Issue by ozdroid** [sonichy/MiniThunder#3]
不知道是否迅雷封锁了。最近这个模块用不了。能Updated一下吗

**Comment by sonichy** [comment]
试了一下，没毛病

**Comment by ozdroid** [comment]
但是最近好像thunder都是文件大小显示-1，我只然后就是111136错误。http文件正常，magnet也好像解析不了。你试是用thunder://链接吗

**Comment by sonichy** [comment]
哦豁，全挂了！
